openvinotoolkit/datumaro

.travis.yml, setup.py
- Added Travis
- Python 3.5 is not included for its EOL
=> Setup Travis

README.md, docs/user_manual.md
=> Update installation docs

datumaro/plugins/coco_format/converter.py, tests/test_coco_format.py
Resolves https://github.com/openvinotoolkit/cvat/issues/2155 introduced in https://github.com/openvinotoolkit/cvat/pull/2000
```python
#
```
=> Fix annotation ids in COCO

docs/developer_guide.md
- Added project, environment, and dataset developer documentation
=> Add project and dataset docs

CHANGELOG.md, datumaro/components/operations.py, tests/test_ops.py
Related #30 
- Fixes zero division in stats computations
Unit tests
```python
#
```
=> Fix division in stats

setup.py
- Added Cython preinstall for pycocotools
```python
#
```
=> Add Cython preinstall for pycocotools

README.md, docs/user_manual.md
- Added ImageNet info in documentation
```python
#
```
=> Add ImageNet to docs

datumaro/plugins/imagenet_format.py
- Fixed converter
```python
#
```
=> Fix ImageNet format

CHANGELOG.md, datumaro/plugins/camvid_format.py, tests/test_camvid_format.py
Fixed extractor and converter for correct testing in CVAT
```python
#
```
=> Fix CamVid format

setup.py
- Added Snyk scan integration
```python
#
```
=> Snyk integration

datumaro/util/test_utils.py, tests/test_camvid_format.py, tests/test_coco_format.py, tests/test_dataset.py, tests/test_imagenet_format.py, tests/test_imagenet_txt_format.py, tests/test_labelme_format.py, tests/test_mot_format.py, tests/test_mots_format.py, tests/test_tfrecord_format.py, tests/test_vgg_face2_format.py, tests/test_voc_format.py, tests/test_widerface_format.py, tests/test_yolo_format.py
- Updated dataset importing in tests to reflect new Dataset API
```python
#
```
=> Update dataset importing in tests

README.md, datumaro/cli/commands/convert.py, datumaro/cli/contexts/project/__init__.py, datumaro/components/dataset.py, tests/test_dataset.py
- Changed arg names and positions in `Dataset.export()` to be consistent with other methods
- Added `Dataset` usage example in `README`
```python
#
```
=> Update dataset export

CHANGELOG.md, datumaro/components/dataset.py, datumaro/components/extractor.py, datumaro/components/project.py, datumaro/plugins/camvid_format.py, datumaro/plugins/image_dir.py, datumaro/plugins/imagenet_format.py, datumaro/plugins/imagenet_txt_format.py, datumaro/plugins/mot_format.py, datumaro/plugins/vgg_face2_format.py, datumaro/plugins/widerface_format.py, datumaro/util/os_util.py, tests/test_util.py
- Allows adding importer-defined formats as project sources
- Extended `Importer.find_sources_recursive`  so that it could filter files by a lambda, specify subdirectory and max search depth
- Fixed affected formats
- Optimized image search in `ImageDir` format - images are recognized by file extension
- Added max search depth in `ImageDir` format
- Added `.tiff` extension in `ImageNet` formats
```python
#
```
=> Allow importer-based project sources

CHANGELOG.md, datumaro/version.py
- Updated version
```python
#
```
=> Release 0.1.5 dev

CHANGELOG.md, datumaro/cli/contexts/model.py, datumaro/components/project.py, docs/user_manual.md
- Fixed model addition docs
- Fixed indentation in docs
- Fixed model copying
```python
#
```
=> Fix model docs

CHANGELOG.md, README.md, docs/design.md, docs/developer_guide.md, docs/user_manual.md
- Updated docs to reflect latest updates
```python
#
```
=> Update changelog and docs

CHANGELOG.md, datumaro/cli/contexts/model.py, datumaro/components/launcher.py, datumaro/plugins/openvino_launcher.py
- Supported OpenVINO 2021.1
- Added extra output layers support with `--output-layers` model property
- Removed `plugins_path` model property
- Fixed inference with single-channel images
- Added auto-removal of model folder on error when adding a model
- Launcher is renamed from `open_vino` to `openvino`
```python
#
```
=> Update OpenVINO launcher for 2021.1

datumaro/components/project.py
- Added missing `ProjectDataset.export` function
```python
#
```
=> Fix project export

datumaro/components/project.py
- Added missing method in `ProjectDataset`
```python
#
```
=> Add missing method

CHANGELOG.md, datumaro/plugins/voc_format/converter.py, tests/test_voc_format.py
- Fixes the regression vs. 0.1.5 with export of empty annotations in VOC format
```python
#
```
=> Save all task data in voc always

datumaro/util/test_utils.py
=> Fix temporary directory removal on windows

datumaro/plugins/sampler/algorithm/algorithm.py, datumaro/plugins/sampler/algorithm/entropy.py, datumaro/plugins/sampler/sampler.py, datumaro/plugins/yolo_format/extractor.py, datumaro/util/test_utils.py, tests/test_sampler.py
- Tests made optional, depending on `pandas` availability
- Updated CLI options
- Updated error messages
```python
#
```
=> Refactor sampler

CHANGELOG.md
Closes #166 
Depends on #169, #170, #171, #172
- Updated changelog
```python
#
```
=> [Dependent] Support arbitrary image extensions in formats (changelog)

datumaro/plugins/image_dir_format.py, datumaro/util/image.py, docs/user_manual.md, tests/test_image_dir_format.py
- Added information about image addition into a project via CLI and API
- Added an option to specify image extensions in ImageDir format
```python
#
```
=> Add image addition info

datumaro/plugins/market1501_format.py, tests/test_market1501_format.py
=> Checking before adding attributes (Market-1501)

datumaro/cli/contexts/project/__init__.py, datumaro/components/validator.py, datumaro/plugins/ndr.py, datumaro/util/__init__.py, tests/test_validator.py
This PR includes:
- Fixes error in validator CLI when serializing a Python dictionary with tuples as keys into JSON format.
- Refactored class interfaces and error messages
- Fixed an error in validator when input dataset does not have LabelCategories
`python -m unittest -v tests/test_validator.py`
```python
#
```
=> Fixes in validator CLI when serializing dictionary with tuple keys to JSON

CHANGELOG.md, datumaro/plugins/icdar_format/extractor.py, tests/test_icdar_format.py
=> Possibility of spaces in label (ICDAR)

CHANGELOG.md, datumaro/plugins/voc_format/converter.py
=> Avoid saving masks in voc when segmentation is not required

CHANGELOG.md
=> Release 0.1.8 (dev)

datumaro/version.py
=> Release 0.1.8 dev - version

CHANGELOG.md
=> Update version in master

README.md, datumaro/cli/contexts/project/__init__.py
- Added a missing conversion option in the example
```python
#
```
=> Fix voc to coco example

CHANGELOG.md, datumaro/components/operations.py, datumaro/plugins/yolo_format/extractor.py, datumaro/util/image.py
- Fixed a possible problem with empty lines on YOLO format loading
- Added type hints in the `Image` class
```python
#
```
=> Ignore empty lines in YOLO annotations

README.md, docs/user_manual.md
Validator documentation is added.
```python
#
```
=> add documentation for validator

docs/user_manual.md
Add validatio item documentation for validator 
```python
#
```
=> add validation item description

CHANGELOG.md, datumaro/plugins/cifar_format.py
- Added folder creation
```python
#
```
=> Fixes in CIFAR dataset format

.github/workflows/coverage.yml
Sending coverage results if python version 3.6
```python
#
```
=> Sending a coverage report if python3.6

.github/pull_request_template.md, README.md
=> Update repo config and badge

.github/workflows/health_check.yml
=> Fix script call

datumaro/cli/__main__.py, tests/requirements.py
- Fixed #268 
- Added `mark_bug` test annotation
```python
#
```
=> Fix help program name, add mark_bug

CHANGELOG.md, datumaro/version.py
=> Release 0.1.9 (dev)

CHANGELOG.md
=> Add changelog stub

CHANGELOG.md, docs/formats/yolo_user_manual.md
=> yolo format documentation update

datumaro/cli/commands/merge.py, datumaro/cli/contexts/project/__init__.py, datumaro/cli/contexts/project/diff.py, datumaro/components/config.py, datumaro/plugins/accuracy_checker_plugin/launcher.py, datumaro/plugins/camvid_format.py, datumaro/plugins/cityscapes_format.py, datumaro/plugins/coco_format/converter.py, datumaro/plugins/coco_format/extractor.py, datumaro/plugins/cvat_format/converter.py, datumaro/plugins/datumaro_format/converter.py, datumaro/plugins/datumaro_format/extractor.py, datumaro/plugins/kitti_format/format.py, datumaro/plugins/mots_format.py, datumaro/plugins/openvino_plugin/launcher.py, datumaro/plugins/openvino_plugin/samples/mobilenet_v2_pytorch_interp.py, datumaro/plugins/openvino_plugin/samples/ssd_mobilenet_coco_detection_interp.py, datumaro/plugins/voc_format/format.py, datumaro/plugins/yolo_format/converter.py
Force utf-8 in all text reading and writing to avoid platform-dependent behaviour of formats.
```python
#
```
=> Force utf-8 everywhere

requirements-core.txt
TensorboardX 2.3 has got support for Comet.ml, but it's implementation has an unlisted dependency on PyTorch. It crashes our CLI.
- Excluded TbX 2.3 from requirements
```python
#
```
=> Fix tensorboardX dependency

docs/formats/open_images_user_manual.md
I accidentally swapped the URLs for test and validation sets.
N/A
```python
#
```
=> open_images_user_manual.md: fix image description file URLs

requirements-core.txt
The regression that #323 worked around has been fixed, so we can now remove the workaround.
```python
#
```
=> Revert #323

datumaro/plugins/datumaro_format/converter.py, datumaro/plugins/datumaro_format/extractor.py, datumaro/plugins/datumaro_format/format.py, datumaro/util/image.py, tests/test_datumaro_format.py
Done the one task from #320.
```python
#
```
=> Cuboid 3D for Datumaro format

CHANGELOG.md
=> Join lines in changelog

CHANGELOG.md, datumaro/plugins/transforms.py, tests/test_transforms.py
- Added bounding boxes values decrement transform (this may be required for some models)
Unit test and manually using the command line
```python
#
```
=> Add bboxes values decrement transform

datumaro/plugins/camvid_format.py
=> Small fix for CamVid Converter

datumaro/plugins/voc_format/converter.py, tests/test_voc_format.py
Fixes the error reported in https://github.com/openvinotoolkit/datumaro/pull/238#issuecomment-871322754
- Fix parsing of lists with unexpected number of elements per line
```python
#
```
=> Fix parsing of lists in VOC

datumaro/components/config.py, datumaro/components/errors.py, tests/test_config.py
- Added more tests
- Improved security of dumping and parsing - complex types are now prohibited
- Improved error reporting and schema validation
- Fixed a `get()` return value
```python
#
```
=> Update Config class

datumaro/util/__init__.py, tests/test_util.py
- Added return value in error_rollback
```python
#
```
=> Fix return value in error_rollback

datumaro/plugins/coco_format/converter.py, datumaro/plugins/coco_format/extractor.py, datumaro/util/os_util.py, datumaro/util/test_utils.py, tests/cli/test_image_zip_format.py, tests/cli/test_kitti_raw_format.py, tests/cli/test_sly_point_cloud_format.py, tests/cli/test_voc_format.py, tests/cli/test_yolo_format.py, tests/test_cvat_format.py, tests/test_dataset.py
- Suppressed cocoapi dataset reading messages (`creating index...`, `index created!`)
- Refactored COCO converter `image.size` uses
- Factored a common function for a checked `datum` execution in CLI tests
```python
#
```
=> Format updates

datumaro/cli/contexts/project/__init__.py, datumaro/cli/contexts/project/diff.py, tests/cli/test_diff.py
- Little improvements for `DatasetDiffVisualizer` implementation
```python
#
```
=> Style fixes for diff visualizer

datumaro/components/converter.py, tests/test_dataset.py, tests/test_widerface_format.py
Closes #348
- Added a generic implementation of dataset patching
```python
#
```
=> Add a generic implementation for patching

CHANGELOG.md, CONTRIBUTING.md, README.md, datumaro/components/extractor.py, datumaro/plugins/cityscapes_format.py, datumaro/util/mask_tools.py, docs/formats/cityscapes_user_manual.md, docs/formats/kitti_raw_user_manual.md, docs/formats/open_images_user_manual.md, docs/user_manual.md
=> Fix various misspellings

.github/workflows/pr_checks.yml
=> Enable CI builds on macOS

CHANGELOG.md, datumaro/components/project.py, tests/requirements.py, tests/test_project.py
=> Fix loading of project plugins

CHANGELOG.md, datumaro/components/project.py, tests/requirements.py, tests/test_project.py
=> Fix string transform name in ProjectDataset

CHANGELOG.md, datumaro/components/extractor.py, datumaro/plugins/transforms.py, tests/requirements.py, tests/test_transforms.py
=> Fix remap_labels for incomplete categories

README.md, site/README.md, site/content/en/docs/_index.md, site/content/en/docs/contribution.md, site/content/en/docs/formats/ade20k2017.md, site/content/en/docs/formats/ade20k2020.md, site/content/en/docs/getting_started.md, site/content/en/docs/user-manual/data-formats.md
This PR fixed the links on the website and in the README.md
```python
#
```
=> Fix the links on the website and in the README.md

site/content/en/docs/formats/ade20k2017.md, site/content/en/docs/formats/ade20k2020.md, site/content/en/docs/formats/cifar.md, site/content/en/docs/formats/cityscapes.md, site/content/en/docs/formats/coco.md, site/content/en/docs/formats/image_zip.md, site/content/en/docs/formats/kitti.md, site/content/en/docs/formats/kitti_raw.md, site/content/en/docs/formats/mnist.md, site/content/en/docs/formats/open_images.md, site/content/en/docs/formats/pascal_voc.md, site/content/en/docs/formats/sly_pointcloud.md, site/content/en/docs/formats/yolo.md
- Format docs now have unified layout
- Fixed ADE20k display on the site
```python
#
```
=> Update format docs

site/content/en/docs/formats/coco.md
=> Add a note about reserved category id in coco

CONTRIBUTING.md, site/content/en/docs/design.md, tests/test_coco_format.py
=> Update contributing guide and design

datumaro/cli/contexts/project/__init__.py, site/content/en/docs/user-manual/_index.md, site/content/en/docs/user-manual/command-reference/_index.md, site/content/en/docs/user-manual/command-reference/projects.md
=> Add migration docs

datumaro/cli/commands/merge.py, datumaro/components/config.py, datumaro/plugins/image_zip_format.py, datumaro/plugins/kitti_raw_format/converter.py, datumaro/plugins/sampler/algorithm/entropy.py, datumaro/plugins/sly_pointcloud_format/converter.py, datumaro/plugins/validators.py
Self-explanatory, I think. :-)
```python
#
```
=> Add missing spaces between words in string literals

CHANGELOG.md, datumaro/components/dataset_filter.py, datumaro/components/extractor.py, datumaro/components/operations.py, datumaro/plugins/datumaro_format/converter.py, tests/test_dataset.py
Removed deprecated `DatasetItem.path` field
```python
#
```
=> Remove DatasetItem.path

requirements-core.txt, requirements-default.txt
=> Update minimal requirements

datumaro/components/dataset_filter.py, datumaro/components/operations.py, datumaro/plugins/cvat_format/converter.py, datumaro/plugins/kitti_raw_format/converter.py, datumaro/plugins/labelme_format.py, datumaro/plugins/voc_format/converter.py, datumaro/util/os_util.py, datumaro/util/tf_util.py
=> Ignore several bandit warnings

site/content/en/docs/formats/_index.md, site/content/en/docs/formats/ade20k2017.md, site/content/en/docs/formats/ade20k2020.md, site/content/en/docs/formats/cifar.md, site/content/en/docs/formats/cityscapes.md, site/content/en/docs/formats/coco.md, site/content/en/docs/formats/image_zip.md, site/content/en/docs/formats/kitti.md, site/content/en/docs/formats/kitti_raw.md, site/content/en/docs/formats/mnist.md, site/content/en/docs/formats/open_images.md, site/content/en/docs/formats/pascal_voc.md, site/content/en/docs/formats/sly_pointcloud.md, site/content/en/docs/formats/yolo.md
This PR improves grammar and wording in individual pages in the Formats section of documentation and makes the pages more uniform
```python
#
```
=> Improving the Formats page in the documentation

datumaro/cli/__main__.py, datumaro/cli/commands/add.py, datumaro/cli/commands/checkout.py, datumaro/cli/commands/commit.py, datumaro/cli/commands/convert.py, datumaro/cli/commands/create.py, datumaro/cli/commands/diff.py, datumaro/cli/commands/explain.py, datumaro/cli/commands/export.py, datumaro/cli/commands/filter.py, datumaro/cli/commands/info.py, datumaro/cli/commands/log.py, datumaro/cli/commands/merge.py, datumaro/cli/commands/remove.py, datumaro/cli/commands/stats.py, datumaro/cli/commands/status.py, datumaro/cli/commands/transform.py, datumaro/cli/commands/validate.py, datumaro/cli/contexts/model.py, datumaro/cli/contexts/project/__init__.py, datumaro/cli/contexts/source.py, datumaro/util/telemetry_stub.py, datumaro/util/telemetry_utils.py, requirements-core.txt, tests/requirements.py, tests/test_telemetry_utils.py
=> Added OpenVINO telemetry

requirements-core.txt, requirements.txt
=> Make telemetry library optional

CHANGELOG.md, requirements-core.txt
=> Update pycocotools version to 2.0.2

CHANGELOG.md
=> Update changelog after #536

CHANGELOG.md, datumaro/plugins/coco_format/importer.py, datumaro/plugins/voc_format/importer.py, tests/test_coco_format.py, tests/test_voc_format.py
=> Implement detection for coco and voc formats

CHANGELOG.md, datumaro/plugins/icdar_format/converter.py, datumaro/util/mask_tools.py, site/content/en/docs/formats/icdar.md, tests/test_icdar_format.py
For exporting dataset into the `icdar_text_segmentation` format, masks of this dataset should have attribute `color`.
So this PR removed such restriction. 
```python
#
```
=> Add generation of colors for ICDAR

tests/test_format_detection.py
See <https://github.com/PyCQA/pylint/issues/5394>.
```python
#
```
=> Work around a pylint regression

.github/workflows/github_pages.yml
Depends on #526 
Updating workflow to generate documentation pages.
**Preview:** https://dvkruchinin.github.io/datumaro/api/
```python
#
```
=> Api documentation sphinx. Update workflow.

.pylintrc, datumaro/plugins/ade20k2017_format.py, datumaro/plugins/ade20k2020_format.py, datumaro/plugins/coco_format/converter.py, datumaro/plugins/datumaro_format/converter.py, datumaro/plugins/widerface_format.py, datumaro/util/meta_file_util.py
Fix all existing instances of bad indentation and enable the corresponding Pylint check so that they do not reoccur.
```python
#
```
=> Enable the bad-indentation Pylint check

.github/workflows/github_pages.yml
This PR fixed incorrect display some sections.
Example:
https://openvinotoolkit.github.io/datumaro/api/api/cli/util/datumaro.cli.util.project.html
https://tosmanov.github.io/datumaro/api/api/cli/util/datumaro.cli.util.project.html
```python
#
```
=> Fix API documentation

.pylintrc, datumaro/plugins/align_celeba_format.py, datumaro/plugins/celeba_format.py, datumaro/plugins/cifar_format.py, datumaro/plugins/coco_format/converter.py, datumaro/plugins/kitti_raw_format/converter.py, datumaro/plugins/labelme_format.py, datumaro/plugins/lfw_format.py, datumaro/plugins/market1501_format.py, datumaro/plugins/mot_format.py, datumaro/plugins/transforms.py, datumaro/plugins/vgg_face2_format.py, datumaro/plugins/voc_format/converter.py, datumaro/plugins/widerface_format.py, site/source/conf.py, tests/test_video.py
=> Enable a few more Pylint checks

site/content/en/docs/formats/pascal_voc.md
=> Replace label_map.txt with labelmap.txt in VOC docs

CHANGELOG.md
=> Add release date in changelog

CHANGELOG.md, datumaro/version.py
=> Update develop from master

site/content/en/docs/user-manual/how_to_use_datumaro.md
fix broken url
```python
#
```
=> fix broken url

site/content/en/docs/user-manual/command-reference/sources.md
=> Fix broken links in sources docs

site/content/en/docs/user-manual/command-reference/sources.md
add more example for add command
add more example for add command
```python
#
```
=> add more example for add command

datumaro/components/annotation.py, datumaro/components/dataset.py, datumaro/components/extractor.py, datumaro/components/extractor_tfds.py, datumaro/components/format_detection.py, datumaro/components/media.py, datumaro/components/project.py, datumaro/plugins/sly_pointcloud_format/converter.py, datumaro/util/scope.py
It's mostly `from __future__ import annotations`.
```python
#
```
=> Upgrade code to use Python 3.7 features

setup.py
Fixes TFDS import problem (https://github.com/tensorflow/datasets/issues/3709) on Windows.
```python
#
```
=> Ban tfds 4.5.0

3rd-party.txt, CHANGELOG.md, MANIFEST.in, datumaro/version.py, setup.py
- Added 3rd-party licenses
- Updated version number
```python
#
```
=> Update develop from master/0.2.3

site/build_docs.py
This PR fixes version generation so that all versions are generated
preview https://tosmanov.github.io/datumaro/docs/
```python
#
```
=> Update documentation site. Fix versions generation

setup.py
4.5.1 doesn't fix the problem, added in 4.5.0.
```python
#
```
=> Ban tfds 4.5.1

CHANGELOG.md, datumaro/plugins/sampler/random_sampler.py, site/content/en/docs/user-manual/command-reference/transform.md, site/source/api/plugins/sampler/datumaro.plugins.sampler.random_sampler.rst, site/source/api/plugins/sampler/datumaro.plugins.sampler.relevancy_sampler.rst, tests/test_sampler.py
Related https://github.com/openvinotoolkit/datumaro/issues/522
- Added a transform to sample images with specific labels
```python
#
```
=> Add label sampling transform

site/content/en/docs/contributing.md, site/content/en/docs/developer_manual.md, site/content/en/docs/formats/cifar.md, site/content/en/docs/formats/cityscapes.md, site/content/en/docs/formats/kitti_raw.md, site/content/en/docs/formats/mnist.md, site/content/en/docs/formats/open_images.md, site/content/en/docs/formats/pascal_voc.md, site/content/en/docs/getting_started.md, site/content/en/docs/user-manual/command-reference/explain.md, site/content/en/docs/user-manual/command-reference/models.md
These are problems I mainly discovered via Pylint:
* Wrong indent size.
* Missing imports.
* Unused variables.
* Typos.
* A few miscellaneous issues.
In addition, replace the old-style `from datumaro.components.*` imports from the affected files with `import datumaro as dm`-style imports. Note that there're many files in `docs/formats` that I haven't touched, so those continue to have old-style imports.
```python
#
```
=> Fix various problems with code snippets in documentation

datumaro/plugins/ndr.py, datumaro/plugins/sampler/random_sampler.py, datumaro/plugins/sampler/relevancy_sampler.py, datumaro/plugins/transforms.py, site/content/en/docs/user-manual/command-reference/transform.md
=> Add docs for transformations

datumaro/cli/commands/detect_format.py, datumaro/cli/commands/diff.py, datumaro/cli/commands/merge.py, datumaro/cli/contexts/project/__init__.py, datumaro/components/project.py, datumaro/plugins/ade20k2020_format.py, datumaro/plugins/coco_format/converter.py, datumaro/plugins/coco_format/extractor.py, datumaro/plugins/datumaro_format/converter.py, datumaro/plugins/datumaro_format/extractor.py, datumaro/plugins/mapillary_vistas_format/extractor.py, datumaro/plugins/mapillary_vistas_format/format.py, datumaro/plugins/mpii_format/mpii_json.py, datumaro/plugins/open_images_format.py, datumaro/plugins/sly_pointcloud_format/converter.py, datumaro/plugins/sly_pointcloud_format/extractor.py, datumaro/plugins/voc_format/format.py, datumaro/plugins/vott_json_format.py, datumaro/util/__init__.py, datumaro/util/meta_file_util.py, requirements-core.txt
For original COCO dataset reading (350 MB json) the speed-up is ~30%, for writing - 10x (which gives ~2.5x speed-up in export). There are some features that can be useful, like builtin `numpy` support.
https://github.com/ijl/orjson
- Replace standard `json` library with `orjson`
- Updated most places (except OpenImages format, where it's not a drop-in replacement)
```python
#
```
=> Change json lib

CHANGELOG.md, datumaro/components/extractor_tfds.py, tests/test_extractor_tfds.py
=> extractor_tfds: Add support for the ImageNetV2 dataset

requirements-core.txt, requirements-default.txt
Telemetry is only supposed for CLI use at this point, so there is no reasons to install it always.
```python
#
```
=> Move telemetry from `core` to `default`

datumaro/components/project.py
- Fixes a file removal error with new DVC release. It happens because this file is no longer autogenerated https://github.com/iterative/dvc/pull/7108 . Error example https://github.com/openvinotoolkit/datumaro/runs/5215565068?check_suite_focus=true
```python
#
```
=> Fix .dvc/plots removal
