datumaro/cli/contexts/project/__init__.py
datumaro/plugins/image_dir.py
datumaro/plugins/transforms.py
datumaro/util/image.py

Resolves https://github.com/opencv/cvat/issues/2132
Resolves https://github.com/opencv/cvat/issues/2137
- Changed default parameter handling for `action='append'` cases in CLI
- Fixed `filter_expr` parameter in the `project filter` command
- Fixed an error in the `image_dir` extractor, which led to image skipping
```python
#
```

Avoid argparse problem, fix image_dir extractor

---

CHANGELOG.md
datumaro/components/operations.py
datumaro/plugins/coco_format/converter.py
datumaro/plugins/cvat_format/converter.py
tests/test_coco_format.py
tests/test_cvat_format.py
tests/test_project.py

Related #16 
- Added the `reindex` option in COCO and CVAT converters to force reindexing (helpful for merging annotations from COCO/CVAT sources)
- Added tests for errors on trying to join datasets with different categories
```python
#
```

Add reindexing option in COCO and CVAT export

---

CHANGELOG.md
datumaro/plugins/labelme_format.py
tests/test_labelme_format.py

Resolves #17 
- Added experimental support for relative image paths in LabelMe format
- Used `filename` and `folder` annotation properties, file names are just numbers
```python
#
```

Support relative paths in LabelMe

---

CHANGELOG.md
datumaro/components/converter.py
datumaro/plugins/tf_detection_api_format/converter.py
datumaro/plugins/tf_detection_api_format/extractor.py
datumaro/plugins/voc_format/converter.py
datumaro/util/image.py
datumaro/util/test_utils.py
tests/test_cvat_format.py
tests/test_images.py
tests/test_voc_format.py

An optimization for images to avoid their decoding and encoding when it is unnecessary, but the data comes not from files on disk, e.g. video frames or downloaded data. In case of jpeg this allows to keep source quality.
Needed to implement raw data copying in CVAT (https://github.com/openvinotoolkit/cvat/pull/2229)
- Added `ByteImage` class to represent encoded images
- Added image data checks in tests, by default enabled when data is available 
- Fixed wrong indentation in VOC format converter, which led to extra disk writes for each image
- Removed `image/depth` field support in VOC converter to avoid unnecessary image reading
- Fixed image extension comparison when extensions in different cases
Unit tests …

Add byte images

---

CHANGELOG.md

- `ByteImage` class to represent encoded images in memory and avoid recoding on save (<https://github.com/openvinotoolkit/datumaro/pull/27>)
- Implementation of format plugins simplified (<https://github.com/openvinotoolkit/datumaro/pull/22>)
- `default` is now a default subset name, instead of `None`. The values are interchangeable. (<https://github.com/openvinotoolkit/datumaro/pull/22>)
- Improved performance of transforms (<https://github.com/openvinotoolkit/datumaro/pull/22>)
- `image/depth` value from VOC export (<https://github.com/openvinotoolkit/datumaro/pull/27>)
- Zero division errors in dataset statistics (<https://github.com/openvinotoolkit/datumaro/pull/31>)

Release v0.1.2 dev

---

datumaro/plugins/mots_format.py
datumaro/plugins/voc_format/converter.py

- Fixed default parameter value for label map in VOC converter
- Fixed exporting empty subsets in MOTS format
```python
#
```

Fix voc and mots converters

---

CHANGELOG.md
datumaro/components/extractor.py
datumaro/plugins/transforms.py

- Fixed random split - it was not random
- Fixed `Transform.subsets()`
```python
#
```

Fix transforms

---

CHANGELOG.md
datumaro/plugins/tf_detection_api_format/converter.py
datumaro/plugins/tf_detection_api_format/format.py
tests/test_tfrecord_format.py

Related #35 
- Fixed unknown image formats on TF Detection API export - they should not lead to errors and produce an empty image format field
- Supported `jpeg` along with `jpg`
```python
#
```

Fix unknown formats in tf detection api export

---

CHANGELOG.md
datumaro/plugins/cvat_format/extractor.py
tests/test_cvat_format.py

Fix empty attributes in CVAT extractor

---

datumaro/plugins/voc_format/importer.py

In some cases developers don't want to specify the exact path to Pascal VOC.
Now you have to specify VOCtrainval_11-May-2012/VOCdevkit/VOC2012/. After the
patch it will be possible to specify VOCtrainval_11-May-2012/.
```python
#
```

Relax importer for Pascal VOC dataset (seach in subdirectories)

---

datumaro/plugins/coco_format/extractor.py

Now it is possible to load coco_instances dataset even if the annotation file doesn't have supercategory.
An internal team tries to load annotations which are generated by an OTE script (https://github.com/openvinotoolkit/training_extensions/blob/develop/pytorch_toolkit/object_detection/model_templates/face-detection/tools/wider_to_coco.py). OTE script doesn't generate supercategory field inside the json annotation file. Probably the field has to be optional.
Feel free to contact the …

Relax coco extractor (none for super category by default)

---

CHANGELOG.md
setup.py

Added ability to install opencv-python-headless dependency instead opencv-python. This is needed for CVAT server Docker image.
Manually
```python
#
```

ability to install opencv-python-headless instead opencv-python

---

CHANGELOG.md
datumaro/version.py

- `CamVid` dataset format (<https://github.com/openvinotoolkit/datumaro/pull/57>)
- Ability to install `opencv-python-headless` dependency with `DATUMARO_HEADLESS=1`
enviroment variable instead of `opencv-python` (<https://github.com/openvinotoolkit/datumaro/pull/62>)
- Allow empty supercategory in COCO (<https://github.com/openvinotoolkit/datumaro/pull/54>)
- Allow Pascal VOC to search in subdirectories (<https://github.com/openvinotoolkit/datumaro/pull/50>)

Release 0.1.4

---

datumaro/plugins/widerface_format.py
tests/test_widerface_format.py

Fixed converter and extractor to work correctly with non-WiderFace attributes
```python
#
```

Fixed WiderFace

---

tests/test_dataset.py
tests/test_project.py

Move dataset tests to a separate file

---

datumaro/plugins/imagenet_format.py
datumaro/plugins/imagenet_txt_format.py

- Fixed the problem #72 (added more extensions for ImageNet and ImageNet_txt)
```python
#
```

Fixed extensions in ImageNet

---

datumaro/plugins/vgg_face2_format.py
tests/test_vgg_face2_format.py

- Added a folder for unlabeled items
```python
#
```

Add a folder for unlabeled items in VggFace2 dataset format

---

CHANGELOG.md
datumaro/plugins/widerface_format.py
tests/assets/widerface_dataset/labels.txt
tests/test_widerface_format.py

- Add label support in WiderFace. In this format, in theory, there should be several bboxes on one label. As a label - some event.
```python
#
```

Add label support in WiderFace dataset format

---

datumaro/components/extractor.py

- Little fix in `_find_sources_recursive`
```python
#
```

Little fix in function for recursive find sources

---

CHANGELOG.md
datumaro/components/extractor.py
datumaro/plugins/coco_format/converter.py
datumaro/plugins/mots_format.py
datumaro/plugins/tf_detection_api_format/converter.py
datumaro/plugins/transforms.py
datumaro/util/mask_tools.py
tests/test_coco_format.py
tests/test_transforms.py

- Added more memory control for mask merging and mask materialization operations
- `merge_masks` can now receive an iterator, which can be helpful for reducing memory consumption
- Improved the memory situation in and fixed #53
- Memory for masks should not be an issue anymore
- There is still can be a problem with low performance, when merging lots of masks (or polygons into masks)
- Significantly improved performance:
- of `masks_to_polygons` (10k x 10k image & 250 masks experiment: 200s -> 30s)
- of `CompiledMask` building (10k x 10k image & 250 masks experiment: 200s -> 80s)
https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using- …

Optimize mask merging and improve memory use

---

CHANGELOG.md
datumaro/components/extractor.py

Follow-up for https://github.com/openvinotoolkit/datumaro/pull/101
- Further optimized mask merging / exporting (10k x 10k image & 250 masks test, 80s -> 60s)
- Masks, covered by other masks with class = 0 (typically - `background`) are now exported correctly with holes inside
```python
#
```

Optimize masks 2

---

datumaro/plugins/icdar_format/converter.py
datumaro/plugins/icdar_format/extractor.py
datumaro/plugins/market1501_format.py
tests/test_icdar_format.py
tests/test_market1501_format.py

ICDAR:
- id replaced with index attribute
- made the color and center attributes to strings
- added checks
Market-1501:
- added saving the file with the names of the images, if `save_images = False`
- added checks
```python
#
```

Fixes in ICDAR and Market-1501 dataset formats

---

datumaro/components/project.py
docs/user_manual.md
tests/test_dataset.py

- Added plugin info in user manual
```python
#
```

Add plugin docs

---

CHANGELOG.md
datumaro/plugins/openvino_launcher.py

Fixes #124 
- Fix inference result when only one output
```python
#
```

Fix inference result when only one output in OpenVINO launcher

---

datumaro/components/converter.py
datumaro/plugins/camvid_format.py
datumaro/plugins/image_dir.py
datumaro/plugins/imagenet_txt_format.py
datumaro/plugins/mot_format.py
datumaro/plugins/mots_format.py
datumaro/plugins/vgg_face2_format.py
datumaro/plugins/voc_format/converter.py
datumaro/plugins/widerface_format.py
datumaro/util/annotation_util.py

- Fixed image saving in VggFace2 and Widerface. Formats should not convert extensions, unless requested
- Refactored image saving in formats
```python
#
```

Refactor image saving in formats, fix vggface2 and widerface

---

CHANGELOG.md
datumaro/plugins/camvid_format.py
datumaro/plugins/imagenet_format.py
datumaro/plugins/imagenet_txt_format.py
datumaro/plugins/lfw_format.py
datumaro/plugins/vgg_face2_format.py
datumaro/plugins/voc_format/converter.py
datumaro/plugins/voc_format/extractor.py
datumaro/plugins/widerface_format.py
datumaro/plugins/yolo_format/converter.py
datumaro/plugins/yolo_format/extractor.py
tests/test_camvid_format.py
tests/test_coco_format.py
tests/test_cvat_format.py
tests/test_datumaro_format.py
tests/test_icdar_format.py
tests/test_image_dir_format.py
tests/test_imagenet_format.py
tests/test_imagenet_txt_format.py
tests/test_labelme_format.py
tests/test_lfw_format.py
tests/test_market1501_format.py
tests/test_mots_format.py
tests/test_tfrecord_format.py
tests/test_vgg_face2_format.py
tests/test_voc_format.py
tests/test_widerface_format.py
tests/test_yolo_format.py

Resolves [openvinotoolkit/cvat#2840](https://github.com/openvinotoolkit/cvat/issues/2840)
Resolves [openvinotoolkit/cvat#2922](https://github.com/openvinotoolkit/cvat/issues/2922)
- Added the ability to work with file names containing Cyrillic and spaces
```python
#
```

Fix dataset formats (cyrilic and spaces in filename)

---

datumaro/plugins/image_dir_format.py
datumaro/plugins/imagenet_format.py
datumaro/plugins/imagenet_txt_format.py
datumaro/util/image.py
datumaro/util/os_util.py
datumaro/util/test_utils.py
tests/test_image_dir_format.py
tests/test_imagenet_format.py
tests/test_imagenet_txt_format.py

- Added image search function
- Renamed image dir to image dir format
- Supported arbitrary image extensions in ImageDir and ImageNet formats
Related #166 
```python
#
```

Support arbitrary image extensions in formats (base + ImageNet, ImageDir)

---

CHANGELOG.md
datumaro/plugins/datumaro_format/converter.py
datumaro/util/image.py
tests/test_dataset.py

- Fixed the problem with occasional image loading in Datumaro format
The problem is that transforms for inputs, providing no image metainfo (`size` etc.), can require image loading for loading size data. Unless image saving is not required, it should not be done.
```python
#
```

Avoid unnecessary image loading in Datumaro format on save

---

CHANGELOG.md
datumaro/plugins/ndr.py
docs/user_manual.md
tests/test_ndr.py

This pr includes :
* CLI support for NDR
* Handle large number of data
`python -m unittest -v tests/test_ndr.py`
```python
#
```

Add ndr cli

---

datumaro/plugins/splitter.py
tests/test_splitter.py

When dataset size is 5 and split ratio is \[train=0.1, val=0.9, test=0.0\], the splitter splits the dataset into [1, 3, 1] instead of [1, 4, 0].
This is a special case of incorrect partitioning due to the inexact round function of python. 
So I fix this bug by ignoring subsets with a near-zero ratio.
```python
#
```

bugfix - ignore subsets of near-zero-ratio

---

CHANGELOG.md
datumaro/components/extractor.py
tests/test_voc_format.py

- Fixed export of instance masks with holes in VOC format
- 'background' class objects don't introduce a new instance on a mask
```python
#
```

Fix export of masks with holes

---

CHANGELOG.md
datumaro/plugins/coco_format/converter.py
datumaro/plugins/voc_format/extractor.py
tests/test_coco_format.py

Closes #183 
- Added an option to save images in COCO in flat layout, disable by default
- Removed conflicting mask attributes in VOC extractor
```python
#
```

Format fixes in COCO and VOC

---

CHANGELOG.md
datumaro/plugins/transforms.py
tests/test_transforms.py

Fixes #201 
- Added more documentation on remap labels behaviour
- Allowed explicit label deletion
- Behaviour is made more accurate
- Fixed debug message
```python
#
```

Make remap labels more accurate

---

CHANGELOG.md
datumaro/plugins/splitter.py
tests/test_splitter.py

Resolve #202 
classification: split unlabeled + multi-labeled data into subsets randomly
detection: split unlabled data into subsets randomly
reidentification: group unlabeled + multi-labeled data as 'not-supported' subset.
```python
#
```

split unlabeled data into subsets for task-specific splitters

---

CHANGELOG.md
datumaro/plugins/cvat_format/converter.py
tests/test_cvat_format.py

Fixes #213 
- Fixed output image format in CVAT export (after #166, affected releases 0.1.7, 0.1.8)
```python
#
```

Fix image saving in cvat format

---

CHANGELOG.md
datumaro/plugins/widerface_format.py
tests/test_widerface_format.py

Added a label "face" for bounding boxes in Wider Face.
```python
#
```

Label "face" for bounding boxes in Wider Face

---

CHANGELOG.md
datumaro/plugins/voc_format/converter.py

Allowed adding "difficult", "truncated", "occluded" attributes when converting to Pascal VOC if these attributes are not present
```python
#
```

Adding "difficult", "truncated", "occluded" attributes when converting to Pascal VOC if they are not present

---

CHANGELOG.md
datumaro/plugins/splitter.py
docs/user_manual.md
tests/test_splitter.py

This PR includes
- Contains splitting for Segmentation Task (Mask and Polygon Annotated Datasets).
- It integrates each splitter plugin into one. (classification_split, detection_split, etc -> split)
- I modified some bugs. Fixed a bug that was calculated as the entire data set length to the labeled data set length.
- Added test code corresponding to segmentation task.
`python3 -m unittest -v tests/test_splitter.py`
```python
#
```

Add splitter for segmentation task 

---

datumaro/cli/contexts/project/__init__.py
datumaro/components/errors.py
datumaro/components/validator.py
tests/test_validator.py

Enhance validator to support instance segmentation
python -m unittest -v tests/test_validator.py
```python
#
```

add validation item for instance segmentation

---

CHANGELOG.md
datumaro/plugins/voc_format/converter.py
tests/test_voc_format.py

Fixed converting to Pascal VOC format for dataset without image data
https://github.com/openvinotoolkit/datumaro/issues/236
Follow the steps to reproduce the bug described in the issue
```python
#
```

Fix converter for Pascal VOC format

---

CHANGELOG.md
datumaro/plugins/widerface_format.py
tests/test_widerface_format.py

Resolves openvinotoolkit/cvat#2944:
- Numeric attributes are stored as string, boolean attributes are stored as boolean.
test
```python
#
```

Fix saving attribute in WiderFace extractor

---

CHANGELOG.md
README.md
datumaro/components/extractor.py
datumaro/components/operations.py
datumaro/plugins/accuracy_checker_plugin/details/ac.py
datumaro/plugins/accuracy_checker_plugin/details/representation.py
datumaro/plugins/cifar_format.py
datumaro/plugins/ndr.py
datumaro/plugins/splitter.py
docs/cli_design.mm
docs/developer_guide.md
docs/formats/cityscapes_user_manual.md
docs/formats/coco_user_manual.md
docs/user_manual.md
tests/cli/test_voc_format.py
tests/test_dataset.py

Fix various misspellings/typos that I found with codespell.
N/A
```python
#
```

Fix spelling errors

---

datumaro/cli/commands/explain.py
datumaro/components/operations.py
datumaro/plugins/cifar_format.py
datumaro/plugins/coco_format/converter.py
datumaro/plugins/coco_format/importer.py
datumaro/plugins/ndr.py
datumaro/plugins/yolo_format/converter.py

Fixes few deprecation warnings
```python
#
```

Fix warnings

---

README.md
datumaro/cli/commands/explain.py
docs/user_manual.md

- Added instructions on RISE usage, examples of model scripts
- Added references in readme
```python
#
```
- TBD: test the instruction

Update RISE docs

---

requirements.txt
setup.py

Avoid 2.0.2 Linux binary distribution because of a conflict in numpy versions with TensorFlow:
- TF is compiled with numpy 1.19 ABI
- pycocotools is compiled with numpy 1.20 ABI
Using a previous version allows to force pycocotools rebuilding, which uses the existing numpy version.
- Fixed #253 
```python
#
```

Fix numpy version conflict

---

tests/requirements.py

When a test fails, Pytest prints the failing test function (with an arrow pointing to the line where the failure occurred). However, with the previous implementation of `mark_requirement`/`mark_bug`, Pytest considers `test_wrapper` as the test function, and so it prints the code of `test_wrapper`, which is useless to the developers.
I rewrote the implementation of `mark_requirement` and `mark_bug` so that an extra wrapper function is no longer created. I also took the opportunity to factor out the decorators applied in both functions.
Just run the unit tests.
- ~~[ ] I have added description of my changes into [CHANGELOG](https://github.com/openvinotoolkit/datumaro/blob/develop/CHANGELOG.md)~~ N/A - no user-facing changes
- ~~[ ] I have updated the [documentation]( …

tests/requirements.py: remove the test_wrapper functions

---

datumaro/cli/contexts/project/diff.py
datumaro/components/dataset.py
datumaro/components/extractor.py
datumaro/components/validator.py
datumaro/plugins/camvid_format.py
datumaro/plugins/cityscapes_format.py
datumaro/plugins/coco_format/converter.py
datumaro/plugins/coco_format/format.py
datumaro/plugins/icdar_format/format.py
datumaro/plugins/kitti_format/converter.py
datumaro/plugins/kitti_format/format.py
datumaro/plugins/mots_format.py
datumaro/plugins/ndr.py
datumaro/plugins/sampler/algorithm/algorithm.py
datumaro/plugins/splitter.py
datumaro/plugins/transforms.py
datumaro/plugins/voc_format/converter.py
datumaro/plugins/voc_format/format.py
datumaro/util/command_targets.py
datumaro/util/image.py

The class style has advantages in terms of IDE support. In particular, with Visual Studio Code, when the functional style is used:
* The enumeration type is considered to be a variable rather than a class.
* Autocomplete doesn't work for enum members.
* "Go to definition" doesn't work for enum members (and indeed, with the functional style they don't really have proper definitions).
Using the class style solves these problems. I would also argue that the class style is slightly more readable due to not as much punctuation (although I can't deny that the repetition of `= auto()` is quite ugly).
The class style removes the need to repeat the enum name twice (in fact, there were a few cases in the codebase in which the two names didn't match).
I converted most of the enums automatically by …

Convert most enum definitions from the functional style to the class style

---

CHANGELOG.md
datumaro/cli/contexts/project/__init__.py
datumaro/components/validator.py
datumaro/plugins/validators.py
tests/test_validator.py

- Improved CLI appearance
- Removed unused imports
- Removed unused code
- Fixed exception raising
- Simplified definitions
```python
#
```

Fix validator definitions

---

CHANGELOG.md
datumaro/util/tf_util.py

Related #269, #146 
- TF availability (avx check) check is made optional in the API and disabled by default
- CLI startup time reduced significantly
This PR disables the most performance-hurting part of CLI startup process. The main reason for this TF availability check
is producing a reasonable error message on TF import failure. As TF is a plugin for Datumaro, it should not affect _all_
users, but those users, who don't need it won't suffer from very long loading time anymore.
For CVAT the provided functionality remains the same, the check is still available via API, but it needs to be enabled.
https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request- …

Make TF availability check optional

---

CHANGELOG.md
datumaro/components/environment.py
datumaro/components/project.py

Closes #269
Related #146 
- Improved CLI startup time by deferring loading of builtin plugins to their use
- `Environment` now provides "push" interface for plugin clients (relative to project config)
Builtin plugins still have uncomfortable loading time, even without TF problem.
```python
#
```

Add lazy loading for builtin plugins

---

datumaro/plugins/coco_format/converter.py
datumaro/plugins/datumaro_format/converter.py
tests/requirements.py
tests/test_coco_format.py
tests/test_datumaro_format.py

Readable COCO and datumaro format for CJK

---

CHANGELOG.md
requirements-core.txt
requirements.txt
setup.py

Currently, all runtime dependencies are listed in both `requirements.txt` and `setup.py`, except that they sometimes have differing version constraints. This is confusing and increases the amount of work a maintainer needs to do when updating the dependency list.
Fix it by moving all runtime dependencies to a separate file (`requirements-core.txt`) and referencing that file from both `setup.py` and `requirements.txt`. Combine all version constraints from both original files.
Unfortunately, some things still need to be duplicated:
* The OpenCV dependency varies depending on environment variables, and that logic can't be replicated with a requirements file. So OpenCV has to be listed separately in `setup.py` and `requirements.txt`.
* Cython is a build dependency, not a runtime dependency, …

Reduce duplication of dependency information

---

requirements-core.txt

See python-pillow/Pillow#5571.
This will hopefully be resolved on Pillow's side soon, at which point we'll be able to revert this. But for now we need this workaround to fix CI.
```python
#
```

Add an upper bound on the Pillow dependency to work around a regression in 8.3

---

CHANGELOG.md
datumaro/plugins/open_images_format.py
docs/formats/open_images_user_manual.md
tests/requirements.py
tests/test_open_images_format.py

This is another step towards implementing #274. This time, I add writing support for metadata, images and labels.
N/A
```python
#
```

Open Images: add writing support

---

datumaro/cli/commands/add.py
datumaro/cli/commands/create.py
datumaro/cli/commands/diff.py
datumaro/cli/commands/ediff.py
datumaro/cli/commands/export.py
datumaro/cli/commands/filter.py
datumaro/cli/commands/import_.py
datumaro/cli/commands/info.py
datumaro/cli/commands/remove.py
datumaro/cli/commands/stats.py
datumaro/cli/commands/transform.py
datumaro/cli/commands/validate.py
datumaro/util/__init__.py
datumaro/util/image.py

This makes all static analyzers happy (rather than just pylint) and ensures
we don't miss any unexpected unused-import issues in the affected files.
N/A
```python
#
```

Remove Pylint unused-import warning suppressions

---

.pylintrc

Put each code on its own line and add a comment with its symbolic name.
That makes the list more understandable and easier to edit.
I could've just used symbolic names instead of codes, but sorting by code
puts related checks next to each other, which I think is helpful.
N/A
```python
#
```

Reformat the enabled checker list in .pylintrc

---

.pylintrc

* Remove obsolete options and checkers.
* Remove the commented-out value of `disable`.
* Use the new code for a checker whose code changed.
N/A
```python
#
```

Clean up .pylintrc

---

.pylintrc
datumaro/plugins/sampler/sampler.py
datumaro/plugins/transforms.py

Invalid escape sequences are deprecated, so fix them and ensure they don't occur again.
```python
#
```

Enable pylint checkers that find invalid escape sequences

---

datumaro/plugins/yolo_format/extractor.py
datumaro/plugins/yolo_format/format.py
datumaro/util/image.py
tests/test_images.py

It looks like the same thing will be needed for Open Images, so I'm
moving it to a common module.
```python
#
```

Factor out the images.meta loading code from YoloExtractor

---

datumaro/components/dataset.py
datumaro/components/extractor.py
datumaro/plugins/coco_format/importer.py
tests/test_dataset.py

- Fixed importing of arbitrary named annotation files in COCO subformats
- Fixed application of transforms when `Dataset.subsets` are called (related #350)
- Optimized `Extractor.get_subset` in the simple case
```python
#
```

Dataset caching fixes

---

CHANGELOG.md
datumaro/plugins/kitti_raw_format/extractor.py
datumaro/plugins/sly_pointcloud_format/converter.py
datumaro/plugins/sly_pointcloud_format/extractor.py
datumaro/plugins/sly_pointcloud_format/format.py
docs/formats/kitti_raw_user_manual.md
docs/formats/sly_pointcloud_user_manual.md
tests/cli/test_kitti_raw_format.py
tests/cli/test_sly_point_cloud_format.py
tests/test_sly_pointcloud_format.py

- Added e2e tests for Supervisely Point Cloud and KITTI Raw formats
- Renamed the `object` attribute to `track_id` in Supervisely Point Cloud
```python
#
```

Add e2e tests for cuboids

---

CHANGELOG.md
datumaro/version.py

Release 0.1.10 (dev)

---

CHANGELOG.md
datumaro/plugins/open_images_format.py
datumaro/util/image.py
docs/formats/open_images_user_manual.md
tests/assets/open_images_dataset_v6/annotations/images.meta
tests/assets/open_images_dataset_v6/annotations/oidv6-train-annotations-bbox.csv
tests/assets/open_images_dataset_v6/annotations/test-annotations-bbox.csv
tests/test_images.py
tests/test_open_images_format.py

This continues the implementation of #274.
You can download some of the bounding boxes for OID, create `images.meta` as described in the documentation and try to import the dataset.
```python
#
```

Open Images: implement bounding box support

---

CHANGELOG.md
datumaro/plugins/cifar_format.py
tests/test_cifar_format.py

- Added class restriction on unpickling in CIFAR import
Unit test, manually on original CIFAR-10/100
```python
#
```

Add class restriction on unpickling in CIFAR import

---

datumaro/components/extractor.py
requirements-core.txt

attrs now supports this functionality natively, so bump the dependency version and replace the workarounds with the native approach.
Resolves #310.
```python
#
```

Remove the __attrs_init__ workarounds

---

CHANGELOG.md
datumaro/plugins/open_images_format.py
tests/test_open_images_format.py

This makes patching work correctly when a subset or annotation type is removed. As a side effect, I also factored out the functionality for lazily creating CSV files into a separate class.
Related to #348.
N/A
```python
#
```

Open Images: remove unneeded annotations when saving in-place

---

CHANGELOG.md
datumaro/components/dataset.py
datumaro/components/extractor.py
datumaro/plugins/camvid_format.py
datumaro/plugins/cityscapes_format.py
datumaro/plugins/yolo_format/converter.py
docs/formats/cityscapes_user_manual.md
tests/cli/test_diff.py
tests/test_camvid_format.py
tests/test_cityscapes_format.py
tests/test_yolo_format.py

Related #348 
- Renamed `MaskCategories.make_default()` to `.generate()`, added an option to include background color
- Fixed dataset patching in YOLO
- Fixed dataset patching in CamVid
- Fixed dataset patching in Cityscapes
- Updated Cityscapes implementation and documentation. Fixed #325, fixed #342. 
- Fixed "background" class in Cityscapes colormaps
- Fixed `Dataset.is_bound` return value
- Added item presence check in `DatasetPatch`
Feel free to contact the maintainers if …

Fix inplace saving in YOLO, CamVid and Cityscapes

---

CHANGELOG.md
datumaro/plugins/imagenet_format.py
tests/cli/test_voc_format.py
tests/test_imagenet_format.py

Resolved #336 by changing id for items.
Import the original ImageNet dataset with Datumaro.
```python
#
```

Fix imagenet importer

---

CHANGELOG.md
datumaro/plugins/icdar_format/extractor.py
tests/test_icdar_format.py

Fixed #374.
Load ICDAR Word Recognition dataset with double quotes in the captions.
```python
#
```

Allow double quotes for ICDAR Word Recognition

---

CHANGELOG.md
requirements-core.txt

The sole usage of it was removed in ce0a122.
```python
#
```

Remove scikit-image from dependencies

---

.pylintrc
datumaro/cli/contexts/model.py
datumaro/cli/contexts/project/__init__.py
datumaro/components/dataset.py
datumaro/util/__init__.py
tests/test_util.py

Instead of adding a global `on_error` variable in the module of the calling function, use a thread-local variable in the `Rollback` class. This has the following advantages:
* Linters and IDEs no longer complain about undefined variables.
* The `Rollback.current` accessor is type-annotated, allowing IDEs to provide autocompletion for methods.
* Using a thread-local variable eliminates potential conflicts if Datumaro is used in multiple threads.
* The `implicit` parameter is no longer required, since we can default to implicit mode if the variable name is unspecified.
Inspired by the discussion in #373.
https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-re …

Redesign the implicit mode of error_rollback

---

datumaro/components/extractor.py
tests/test_cifar_format.py

- Fixed the problem with CIFAR export and checking dataset in importer (annotation files haven't extensions)
```python
#
```

Allow direct matching of files without extension in _find_sources_recursive

---

.pylintrc
datumaro/cli/commands/merge.py
datumaro/plugins/accuracy_checker_plugin/details/representation.py
datumaro/util/annotation_util.py

Undefined variables are a serious problem, and easy to check for, so do that and fix all existing occurrences.
~~WRT the `error_rollback` changes: there was no error there, but Pylint would complain, because it didn't know where the `on_error` variable was coming from. Defining `on_error` explicitly is the workaround for that. While it's less elegant, it makes the code more transparent, both for human users and static analyzers (such as Pylint itself, or VS Code's syntax checker). Also, IMO, the benefits of the checker far outweigh the drawback of having to implement this workaround.~~
https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue …

Enable the Pylint undefined-variable checker

---

.github/workflows/pr_checks.yml
CHANGELOG.md
datumaro/plugins/icdar_format/extractor.py
datumaro/plugins/market1501_format.py
datumaro/plugins/vgg_face2_format.py
datumaro/plugins/voc_format/extractor.py
datumaro/util/image.py

Add Windows CI builds and fix/work around any issues that they found.
```python
#
```

Add CI on Windows

---

CHANGELOG.md
datumaro/plugins/cvat_format/extractor.py
tests/assets/cvat_dataset/for_images/train.xml
tests/test_cvat_format.py

Fix attributes casting for CVAT format

---

.github/workflows/github_pages.yml
site/build_docs.py

Adding the GitHub pages generation functionality.
```python
#
```

GitHub pages.

---

site/layouts/partials/navbar-version-selector.html

This PR added `navbar-version-selector.html` to ensure that when you change the version, the current page in a different version opens and not the root of the site
```python
#
```

Add navbar-version-selector.html for documentation website

---

site/content/en/page_404.html
site/layouts/404.html

This PR contains fix page 404.
The page was corrected by a redirect in the `404` template, the redirect leads to the created page `page_404` at the root of the site
Preview: 
https://tosmanov.github.io/datumaro/2134
https://tosmanov.github.io/datumaro/docs/usr_manual
```python
#
```

Fix page 404 on documentation website

---

CHANGELOG.md
datumaro/plugins/open_images_format.py

`np.bool` was deprecated in NumPy 1.20 in favor of plain `bool`.
```python
#
```

Fix a deprecation warning in open_images_format

---

CHANGELOG.md
datumaro/util/image.py

Currently, the key used to look up the cached image is based on a hash of a tuple containing `id(self)`, `path`, and `loader`. This means there are two situations in which a `lazy_image` can look up the wrong data:
* If there previously existed another `lazy_image` object whose `self` and `loader` had the same object IDs as the current `lazy_image`'s `self` and `loader`. This is possible, because deleted objects' IDs can be reused.
* If a hash collision occurs between the current `lazy_image`'s tuple and some other's.
Fix it by using a weak reference to `self` as the key instead. Different weak references will only compare equal if they point to the same object.
This will only work correctly if the loader and path of a `lazy_image` are not modified after creation. I don't think there are …

lazy_image: fix cache collisions leading to unrelated data being returned

---

CHANGELOG.md
datumaro/cli/contexts/model.py
datumaro/cli/contexts/project/__init__.py
datumaro/components/converter.py
datumaro/components/dataset.py
datumaro/util/__init__.py
datumaro/util/scope.py
tests/test_util.py

Replaces error rollback utilities with scope utilities. The new class extends the previous situation to be like try-except-finally and allows to enter context managers. This helps to maintain flat code indentation and helps with the objects that require closing / disposal in any cases (i.e. resource managers). The `Project` class is going to be such a manager - this is needed to resolve problems with file removal on Windows.
Feel free to contact the maintainers if that's a …

Replace Rollback with Scope

---

CHANGELOG.md
datumaro/util/mask_tools.py

The `pyiscrowd` parameter is supposed to have the same length as `gt`, which in this case is 1, not 2. This mistake used to be harmless, but an assert for this was added in the upstream repository (see ppwwyyxx/cocoapi@4f034008), so if a new release of pycocotools comes out, the current version will start crashing.
```python
#
```

Fix an invalid call to pycocotools.mask.iou

---

CHANGELOG.md
datumaro/plugins/widerface_format.py

- Fixed saving the name of the test subset
- Changed: If there are no bounding boxes, only the image name is written to the file (previously, zero was written)
manually on the widerface dataset
```python
#
```

Fix reading, writing anno file and saving name of the subset for test subset

---

CHANGELOG.md
datumaro/cli/contexts/source.py
datumaro/plugins/coco_format/extractor.py
datumaro/plugins/coco_format/importer.py
site/content/en/docs/formats/coco.md
tests/assets/coco_dataset/coco/annotations/instances_train.json
tests/assets/coco_dataset/coco/annotations/instances_val.json
tests/assets/coco_dataset/coco_instances/annotations/instances_train.json
tests/assets/coco_dataset/coco_instances/annotations/instances_val.json
tests/test_coco_format.py

This is needed for potential integration into Accuracy Checker, since AC has this option as well.
As a side effect, refactor the loading of categories to remove duplication between the panoptic segmentation and other task types.
```python
#
```

coco_format: add an option to preserve original category IDs when extracting

---

datumaro/cli/contexts/project/__init__.py
datumaro/cli/contexts/source.py
datumaro/components/config.py
datumaro/components/project.py
datumaro/util/os_util.py
datumaro/util/test_utils.py
site/content/en/docs/formats/cityscapes.md
site/content/en/docs/formats/coco.md
site/content/en/docs/formats/kitti.md
site/content/en/docs/formats/kitti_raw.md
site/content/en/docs/formats/pascal_voc.md
site/content/en/docs/formats/sly_pointcloud.md
site/content/en/docs/user-manual/command-reference/sources.md
site/content/en/docs/user-manual/how_to_use_datumaro.md
tests/cli/test_project.py
tests/test_config.py
tests/test_project.py

- Added `--no-hash` option in `Project.import_source()`. The option is enabled by default, so no hashing is performed until commit is requested.
- Allowed `Pipeline` arguments in `Tree.make_dataset()`
- Removed output hashing in modifying CLI operations (`datum filter`, `datum transform`)
- Added cache status info in `project info` output
- Fixed `Config` copying with recursive structures - `Config` instances do recursive copying
- Fixed `TestDir` behavior on Windows in case of errors - test errors are not shadowed by `SkipTest` errors from `git.utils.rmtree` anymore. …

Import without hashing

---

tests/test_util.py

Added missed pytest marking.

---

datumaro/plugins/kitti_format/extractor.py
datumaro/plugins/kitti_format/importer.py
tests/test_datumaro_format.py
tests/test_icdar_format.py
tests/test_imagenet_txt_format.py
tests/test_kitti_format.py
tests/test_lfw_format.py
tests/test_mot_format.py
tests/test_mots_format.py
tests/test_widerface_format.py

Some formats does not have tests for importing dataset without images. So I added such tests.
And also fixed Kitti format.
```python
#
```

Add tests for dataset importing without images

---

CHANGELOG.md
datumaro/cli/__main__.py
datumaro/cli/commands/__init__.py
datumaro/cli/commands/diff.py
datumaro/cli/commands/patch.py
datumaro/components/annotation.py
datumaro/components/dataset.py
datumaro/components/errors.py
datumaro/components/extractor.py
datumaro/components/project.py
datumaro/plugins/coco_format/converter.py
datumaro/plugins/open_images_format.py
datumaro/plugins/transforms.py
datumaro/util/annotation_util.py
datumaro/util/telemetry_utils.py
site/content/en/docs/formats/coco.md
site/content/en/docs/user-manual/_index.md
site/content/en/docs/user-manual/command-reference/_index.md
site/content/en/docs/user-manual/command-reference/patch.md
tests/cli/test_patch.py
tests/test_dataset.py
tests/test_project.py
tests/test_transforms.py

- Added `datum patch` command, which allows to update a dataset from another dataset
- Added command docs
- Added `ProjectLabels` transform to align dataset labels
- Added label existence check in `LabelCategories` by name
- Added an error message on attempt to re-download a source with no hash
- Improved COCO export docs
- Fixed return value type in `Dataset.is_modified`
- Fixed missing error on saving project readonly project datasets inplace by path
- Fixed class inheritance for `DatasetMergeError` (`item_id` should not be mandatory)
- Fixed sensitive args in `datum diff`
- Fixed label remapping for secondary categories in `RemapLabels`
https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull …

Add patch command

---

datumaro/components/annotation.py
datumaro/components/extractor.py
datumaro/components/operations.py

The attrs documentation says that this approach is preferred for Python 3.6+, and the next-generation API (`attr.field`) doesn't include the `type` argument at all.
In the cases of `AnnotationMatcher._context` and `PointsMatcher.sigma`, change the type to `Optional`, since otherwise the default value won't match it.
Related to #310.
```python
#
```

Use variable annotations instead of attrib(type=...)

---

datumaro/plugins/mapillary_vistas_format/extractor.py

This module ended up with a broken import due to #537 and #538 being merged at roughly the same time.
```python
#
```

mapillary_vistas_format: fix image import

---

datumaro/components/format_detection.py
datumaro/plugins/ade20k2017_format.py
datumaro/plugins/ade20k2020_format.py
datumaro/plugins/cvat_format/extractor.py
datumaro/plugins/datumaro_format/extractor.py
datumaro/plugins/icdar_format/extractor.py
datumaro/plugins/kitti_raw_format/extractor.py
datumaro/plugins/labelme_format.py
datumaro/plugins/mot_format.py
datumaro/plugins/yolo_format/extractor.py
tests/cli/test_revpath.py
tests/test_ade20k2017_format.py
tests/test_ade20k2020_format.py
tests/test_cvat_format.py
tests/test_datumaro_format.py
tests/test_icdar_format.py
tests/test_kitti_raw_format.py
tests/test_labelme_format.py
tests/test_mot_format.py
tests/test_yolo_format.py

Add detectors for a few more dataset formats:
* `ade20k2017`
* `ade20k2020`
* `cvat`
* `datumaro`
* `icdar_text_segmentation`
* `icdar_word_recognition`
* `kitti_raw`
* `label_me`
* `mot_seq`
* `yolo`
To support them, add a mechanism for placing requirements on file contents.
```python
#
```

Add more dataset format detectors

---

.github/workflows/pr_checks.yml
CHANGELOG.md
requirements-core.txt

Use the original `pycocotools` PyPI package, since `pycocotools-windows` does not have wheels for Python 3.9+. `pycocotools` doesn't have wheels either, but at least it's buildable from source.
```python
#
```

Unblock install on Python 3.9+ on Windows

---

requirements.txt
setup.py

These were originally needed for pycocotools; however, since version 2.0.1 pycocotools will fetch Cython by itself.
In addition, `Distribution.fetch_build_eggs` is an undocumented function, and given that setuptools has been deprecating its distribution-fetching functionality (like `easy_install` and `setup_requires`), its days might be numbered.
```python
#
```

Remove Cython-related workarounds

---

CHANGELOG.md
datumaro/components/format_detection.py
datumaro/plugins/lfw_format.py
datumaro/plugins/open_images_format.py
datumaro/plugins/vgg_face2_format.py
datumaro/plugins/widerface_format.py
tests/test_format_detection.py
tests/test_lfw_format.py
tests/test_open_images_format.py
tests/test_widerface_format.py

The formats in question are `lfw`, `open_images`, `vgg_face2` and `widerface`. As supporting infrastructure, add alternative requirement support.
Also, add low-level format detection tests, which I should really have done earlier.
```python
#
```

Add detection support for 4 more formats

---

CHANGELOG.md
datumaro/components/format_detection.py
datumaro/plugins/camvid_format.py
datumaro/plugins/imagenet_txt_format.py
tests/test_camvid_format.py
tests/test_format_detection.py
tests/test_imagenet_txt_format.py

As a supporting mechanism, add a way to exclude some files to `require_file`.
```python
#
```

Add detection support for the camvid and imagenet_txt formats

---

CHANGELOG.md
datumaro/components/media.py
tests/test_images.py

This support has some questionable semantics:
* It's not symmetric (`Image` can be equal to `ndarray`, but not the other way around).
* It doesn't behave the same as `ndarray` comparison (which returns an `ndarray` rather than `bool`), so it's not quite transitive either (if `image == array1` and `image == array2` are true, then `array1 == array2` is not true (but an array of `True`s).
Moreover, it's seemingly only used in two tests, and those tests can easily use `np.testing.assert_array_equal` instead, which has the added benefit of printing detailed mismatch information.
Inspired by the discussion in #521.
https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a- …

Remove the `Image`<->`np.ndarray` equality comparison support

---

CHANGELOG.md
datumaro/plugins/kitti_format/converter.py
datumaro/plugins/kitti_format/extractor.py
datumaro/plugins/kitti_format/format.py
site/content/en/docs/formats/kitti.md
tests/test_kitti_format.py

Support of score attribute in KITTI detetion

---

datumaro/components/dataset.py
datumaro/components/extractor.py
datumaro/components/project.py

`__iter__` is supposed to return an iterator, not an iterable (the object
with the `__iter__` method is the iterable).
```python
#
```

Fix type annotations on some `__iter__` methods

---

site/build_docs.py
site/config.toml

See the individual commits for details. The important commit (the one I started this whole thing for) is the last one; it's also the only commit that affects the output. The rest are just improvements I made along the way.
Run the script.
```python
#
```

Make various improvements to site/build_docs.py

---

CHANGELOG.md
datumaro/components/operations.py
datumaro/util/annotation_util.py
tests/test_ops.py

Closes #219 
- Renamed `smooth_line` to `approximate_line`, added deprecation notice
- Added more descriptions and type annotations
- The function now always returns only a single array
- Updated implementation of the line comparison algorithm
- Fixed the problem when multimerge failed because of missing label categories
- Fixed area computation in case of self-intersections
```python
#
```

Fix line matching in multimerge

---

CHANGELOG.md
datumaro/components/media.py
tests/test_images.py

This lets us avoid needless re-encoding when a `ByteImage` is saved as the format it already is in.
Unfortunately, neither OpenCV nor PIL seem to offer functionality to detect the format without loading the image, so we have to implement it ourselves. I only added support for a handful of most common formats, which should cover a majority of cases.
```python
#
```

ByteImage: try to guess the image extension if one is not given

---

.github/workflows/github_pages.yml
site/README.md
site/source/_static/custom.css
site/source/conf.py

This PR added API documentation versioning.
For versioning used [`sphinxcontrib-versioning fork`](https://github.com/pytorch-ignite/sphinxcontrib-versioning), because the main repository has not received updates for a long time.
After datumaro release `v0.2.2`, it is version will display on the version menu.
Preview: https://tosmanov.github.io/datumaro/api/
```python
#
```

Add API documentation versioning

---

requirements-default.txt

Closes #612 
Recent release of GitPython introduced a regression on Windows. This PR avoids this regression by disabling GitPython==3.1.25.
```python
#
```

Avoid PermissionError in GitPython 3.1.25

---

.github/workflows/health_check.yml
.github/workflows/pr_checks.yml
CHANGELOG.md
requirements-core.txt
requirements.txt
site/content/en/docs/user-manual/installation.md

Ignore this for now. I'm just making sure that the changes I made in ppwwyyxx/cocoapi#6 do actually resolve the issues for which the workarounds were added.
```python
#
```

Remove hacks that were added to work around issues in pycocotools

---

.github/workflows/health_check.yml
.github/workflows/pr_checks.yml
CHANGELOG.md
datumaro/util/attrs_util.py
setup.py
site/content/en/docs/contributing.md
site/content/en/docs/getting_started.md
site/content/en/docs/user-manual/installation.md

Python 3.6 [is EOLed](https://www.python.org/dev/peps/pep-0494/#schedule-last-security-only-release), so it's reasonable to discontinue it's support. Moreover, we already use some features of 3.7 (currently, only to make API changes backward-compatible).
- Changed the minimum required version in `setup.py`
```python
#
```

Mark python 3.6 unsupported

---

CHANGELOG.md
datumaro/components/project.py
tests/requirements.py
tests/test_project.py

Closes #602 
- Changed how dataset path is stored in `ProjectDataset` to use only the source directory. This follows the logic of how project contains sources and allows to save/export/patch project datasets in essential way.
```python
#
```

Fix project dataset saving when rpath is used

---

site/content/en/docs/user-manual/command-reference/checkout.md
site/content/en/docs/user-manual/command-reference/commit.md
site/content/en/docs/user-manual/command-reference/convert.md
site/content/en/docs/user-manual/command-reference/create.md
site/content/en/docs/user-manual/command-reference/diff.md
site/content/en/docs/user-manual/command-reference/download.md
site/content/en/docs/user-manual/command-reference/explain.md
site/content/en/docs/user-manual/command-reference/export.md
site/content/en/docs/user-manual/command-reference/filter.md
site/content/en/docs/user-manual/command-reference/info.md
site/content/en/docs/user-manual/command-reference/log.md
site/content/en/docs/user-manual/command-reference/merge.md
site/content/en/docs/user-manual/command-reference/models.md
site/content/en/docs/user-manual/command-reference/patch.md
site/content/en/docs/user-manual/command-reference/projects.md
site/content/en/docs/user-manual/command-reference/sources.md
site/content/en/docs/user-manual/command-reference/stats.md
site/content/en/docs/user-manual/command-reference/status.md
site/content/en/docs/user-manual/command-reference/transform.md
site/content/en/docs/user-manual/command-reference/util.md
site/content/en/docs/user-manual/command-reference/validate.md

* Use each command's name as the corresponding link title.
* Remove all weights from the command pages, which has the effect of ordering
them by link title (i.e., by name).
This makes the command reference usable as an actual reference, because you
can now look up commands by name.
It also simplifies documentation maintenance, because there are fewer things
you need to configure when adding a new command.
```python
#
```

Reorganize the TOC for the command reference

---

site/content/en/docs/user-manual/command-reference/_index.md

* Use meaningful identifiers for nodes so that we don't need to renumber them when adding new commands in the middle. (This also fixes duplicate IDs for the `create` and `download` commands, which I accidentally caused in a28b32db6).
* Order commands within a group and contexts alphabetically, to make the diagram easier to navigate.
The reason there's an underscore in front of each node ID corresponding to a command not in a context is that Mermaid refuses to render a graph if a node has "filter" as the ID. Don't know what's up with that. …

Reformat the diagram of datum subcommands

---

CHANGELOG.md
datumaro/cli/__main__.py
datumaro/cli/commands/__init__.py
datumaro/cli/commands/detect_format.py
datumaro/components/environment.py
datumaro/components/format_detection.py
site/content/en/docs/user-manual/_index.md
site/content/en/docs/user-manual/command-reference/_index.md
site/content/en/docs/user-manual/command-reference/detect-format.md
tests/cli/test_detect_format.py
tests/test_format_detection.py

Add a dedicated command to detect a dataset's format

---

site/content/en/docs/user-manual/command-reference/detect-format.md

I forgot to update it after I changed the "message" field from a list to a string.
```python
#
```

Fix the format-message JSON report description

---

CHANGELOG.md
datumaro/plugins/sampler/random_sampler.py
datumaro/plugins/sampler/relevancy_sampler.py
site/content/en/docs/user-manual/command-reference/transform.md
site/source/api/plugins/sampler/datumaro.plugins.sampler.random_sampler.rst
site/source/api/plugins/sampler/datumaro.plugins.sampler.relevancy_sampler.rst
tests/test_sampler.py

- Adds a random sampler, which allows quickly extract smaller datasets with randomly-selected items
- Regular sampler renamed to relevancy sampler for clarity and better distinction
```python
#
```

Add random sampler transform

---

datumaro/components/annotation.py
datumaro/plugins/coco_format/extractor.py
requirements-core.txt
setup.py

Experiments have shown that COCO import is quite slow:
```
from datumaro.components.dataset import Dataset
dataset = Dataset.import_from('coco/', 'coco_instances') # train + val 2014
dataset.init_cache()
```
Works ~57s on my machine. This patch does some refactoring to make loading faster.
- Dont use pycocotools for parsing (no benefits at all except format logic encapsulation) (dropping gives ~6s / 10% speedup)
- Allow lazy rle and make masks lazy
Parsing can be further improved by using more performant json library (`orjson` gives ~3s speedup), it can be done in another PR separately.
https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issu …

Refactor COCO parsing

---

datumaro/__init__.py
datumaro/errors.py
datumaro/ops.py
datumaro/project.py
site/source/api/datumaro.rst
tests/requirements.py
tests/test_api.py

Fixes the problems with importing of symbols from module aliases in API using `from x import y`.
- Added proxy modules for module aliases in API
- Added API tests
```python
#
```

Fix import of module aliases in API

---

.github/workflows/health_check.yml
.github/workflows/pr_checks.yml

Since we just disabled 3.6, it seems logical to enable the most recent release, 3.10.
```python
#
```

Enable CI on Python 3.10

---

CHANGELOG.md
datumaro/components/extractor_tfds.py
tests/test_extractor_tfds.py

Try to download it yourself:
```
$ datum download -i tfds:coco/2014 -o coco-2014
```
For more extreme testing, add `-- --save-images`. :P
```python
#
```

extractor_tfds: add support for downloading COCO

---

CHANGELOG.md
datumaro/components/format_detection.py
datumaro/plugins/coco_format/importer.py
datumaro/plugins/voc_format/importer.py
site/content/en/docs/user-manual/command-reference/detect-format.md
tests/test_format_detection.py

Currently, instances where detection for a format is unsupported are reported via `context.fail`. However, `context.fail` is intended primarily for situations where the dataset fails some requirement, and using it for this leads to unnatural-looking messages:
The following requirement was not met:
this format cannot be autodetected
Fix this by adding a dedicated rejection reason for this case and a new method, `context.raise_unsupported` to abort detection for this reason.
Feel …

format_detection: add a dedicated function to report unsupported detection

---

datumaro/plugins/market1501_format.py
datumaro/util/__init__.py

`distutils` has been deprecated in Python 3.10. Fortunately, the only name we're using from there is `strtobool`, and conveniently, `attrs` has recently added a function with the same semantics and the same sets of true and false values. So just use that instead.
Note that `strtobool` is still used in `setup.py`, and we can't use `attrs` there. I'm hoping that setuptools will eventually provide a replacement.
```python
# …
```

Remove usages of distutils from the library

---

CHANGELOG.md
datumaro/components/extractor_tfds.py
datumaro/plugins/market1501_format.py
datumaro/util/__init__.py
tests/test_extractor_tfds.py

The main nuisance with this is that Datumaro represents the pose as a string, while TFDS represents it as an index, and to convert the latter into the former, we need access to the list of poses.
To implement this, allow adapters access to a persistent state object that can be used to store and retrieve arbitrary data during conversion. We can then save the list of names during category creation and retrieve it when we convert box annotations.
Feel free to contact the …

Save box attributes when downloading the TFDS version of VOC
